# Generated by Django 5.1.4 on 2024-12-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_remitente', models.CharField(max_length=100)),
                ('direccion_origen', models.CharField(max_length=255)),
                ('direccion_destino', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=100)),
                ('origen', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('fecha_envio', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pasajero', models.CharField(max_length=100)),
                ('direccion_origen', models.CharField(max_length=255)),
                ('direccion_destino', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=100)),
                ('origen', models.CharField(choices=[('Barranquilla', 'Barranquilla'), ('Galeras', 'Galeras'), ('Since', 'Since'), ('Sincelejo', 'Sincelejo'), ('Betulia', 'Betulia'), ('Corozal', 'Corozal'), ('Ovejas', 'Ovejas')], max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('fecha_viaje', models.DateField()),
                ('hora_viaje', models.TimeField()),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad_pasajes', models.PositiveIntegerField(default=1)),
                ('ruta', models.CharField(max_length=50)),
            ],
        ),
    ]
