# Generated by Django 5.1.4 on 2025-07-11 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_destino', models.CharField(max_length=255)),
                ('origen', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('fecha_envio', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('Barranquilla', 'Barranquilla'), ('Galeras', 'Galeras'), ('Since', 'Sincé'), ('Sincelejo', 'Sincelejo'), ('Betulia', 'Betulia'), ('Corozal', 'Corozal'), ('Ovejas', 'Ovejas')], max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('fecha_viaje', models.DateField()),
                ('hora_viaje', models.TimeField()),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad_pasajes', models.PositiveIntegerField(default=1)),
                ('ruta', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
            ],
        ),
    ]
